//go:build gonavi_full_drivers

package db

func registerOptionalDatabaseFactories() {
	registerDatabaseFactory(newOptionalDriverAgentDatabase("goldendb"), "goldendb", "greatdb", "gdb")
	registerDatabaseFactory(newOptionalDriverAgentDatabase("oracle"), "oracle")
	registerDatabaseFactory(newOptionalDriverAgentDatabase("chroma"), "chroma", "chromadb", "chroma-db")
	registerDatabaseFactory(newOptionalDriverAgentDatabase("qdrant"), "qdrant", "qdrantdb", "qdrant-db")
	registerDatabaseFactory(newOptionalDriverAgentDatabase("rocketmq"), "rocketmq", "rocket-mq", "rocket_mq", "apache-rocketmq", "apache_rocketmq", "rmq")
	registerDatabaseFactory(newOptionalDriverAgentDatabase("mqtt"), "mqtt", "mqtts")
	registerDatabaseFactory(newOptionalDriverAgentDatabase("kafka"), "kafka", "apache-kafka", "apache_kafka")
	registerDatabaseFactory(newOptionalDriverAgentDatabase("rabbitmq"), "rabbitmq", "rabbit-mq", "rabbit_mq")
	registerDatabaseFactory(newOptionalDriverAgentDatabase("mariadb"), "mariadb")
	registerDatabaseFactory(newOptionalDriverAgentDatabase("oceanbase"), "oceanbase")
	registerDatabaseFactory(newOptionalDriverAgentDatabase("diros"), "diros", "doris")
	registerDatabaseFactory(newOptionalDriverAgentDatabase("starrocks"), "starrocks")
	registerDatabaseFactory(newOptionalDriverAgentDatabase("sphinx"), "sphinx")
	registerDatabaseFactory(newOptionalDriverAgentDatabase("sqlserver"), "sqlserver")
	registerDatabaseFactory(newOptionalDriverAgentDatabase("sqlite"), "sqlite")
	registerDatabaseFactory(newOptionalDriverAgentDatabase("duckdb"), "duckdb")
	registerDatabaseFactory(newOptionalDriverAgentDatabase("dameng"), "dameng")
	registerDatabaseFactory(newOptionalDriverAgentDatabase("kingbase"), "kingbase")
	registerDatabaseFactory(newOptionalDriverAgentDatabase("highgo"), "highgo")
	registerDatabaseFactory(newOptionalDriverAgentDatabase("vastbase"), "vastbase")
	registerDatabaseFactory(newOptionalDriverAgentDatabase("opengauss"), "opengauss", "open_gauss", "open-gauss")
	registerDatabaseFactory(newOptionalDriverAgentDatabase("gaussdb"), "gaussdb", "gauss_db", "gauss-db")
	registerDatabaseFactory(newOptionalDriverAgentDatabase("iris"), "iris", "intersystems")
	registerDatabaseFactory(newOptionalDriverAgentDatabase("mongodb"), "mongodb")
	registerDatabaseFactory(newOptionalDriverAgentDatabase("tdengine"), "tdengine")
	registerDatabaseFactory(newOptionalDriverAgentDatabase("iotdb"), "iotdb", "apache-iotdb", "apache_iotdb")
	registerDatabaseFactory(newOptionalDriverAgentDatabase("clickhouse"), "clickhouse")
	registerDatabaseFactory(newOptionalDriverAgentDatabase("elasticsearch"), "elasticsearch", "elastic")
	registerDatabaseFactory(newOptionalDriverAgentDatabase("trino"), "trino")
}
